Document: grove-py
Title: Debian grove-py Manual
Author: <insert document author here>
Abstract: This manual describes what grove-py is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/grove-py/grove-py.sgml.gz

Format: postscript
Files: /usr/share/doc/grove-py/grove-py.ps.gz

Format: text
Files: /usr/share/doc/grove-py/grove-py.text.gz

Format: HTML
Index: /usr/share/doc/grove-py/html/index.html
Files: /usr/share/doc/grove-py/html/*.html
