#!/bin/bash -e

mkdir -p /sys/kernel/config/usb_gadget/g
echo 0x1d6b > /sys/kernel/config/usb_gadget/g/idVendor  # Linux Foundation
echo 0x0104 > /sys/kernel/config/usb_gadget/g/idProduct # Multifunction Composite Gadget
echo 0x0100 > /sys/kernel/config/usb_gadget/g/bcdDevice # v1.0.0
echo 0x0200 > /sys/kernel/config/usb_gadget/g/bcdUSB    # USB 2.0
echo 0xef > /sys/kernel/config/usb_gadget/g/bDeviceClass    # USB 2.0
echo 0x02 > /sys/kernel/config/usb_gadget/g/bDeviceSubClass    # USB 2.0
echo 0x01 > /sys/kernel/config/usb_gadget/g/bDeviceProtocol    # USB 2.0

mkdir -p  /sys/kernel/config/usb_gadget/g/strings/0x409
echo "respeaker2201708"         > /sys/kernel/config/usb_gadget/g/strings/0x409/serialnumber
echo "Seeed Studio"             > /sys/kernel/config/usb_gadget/g/strings/0x409/manufacturer
echo "ReSpekaer V2 Gadget"      > /sys/kernel/config/usb_gadget/g/strings/0x409/product    

mkdir -p /sys/kernel/config/usb_gadget/g/functions/acm.usb0    # serial
#mkdir -p /sys/kernel/config/usb_gadget/g/functions/rndis.usb0  # network
#mkdir -p /sys/kernel/config/usb_gadget/g/functions/uac2.usb0   # audio

mkdir -p /sys/kernel/config/usb_gadget/g/configs/c.1
echo 250 > /sys/kernel/config/usb_gadget/g/configs/c.1/MaxPower

#ln -s /sys/kernel/config/usb_gadget/g/functions/rndis.usb0 /sys/kernel/config/usb_gadget/g/configs/c.1/
ln -s /sys/kernel/config/usb_gadget/g/functions/acm.usb0   /sys/kernel/config/usb_gadget/g/configs/c.1/
#ln -s /sys/kernel/config/usb_gadget/g/functions/uac2.usb0  /sys/kernel/config/usb_gadget/g/configs/c.1/  

udevadm settle -t 5 || :
ls /sys/class/udc/ > /sys/kernel/config/usb_gadget/g/UDC 
if [ -d /sys/class/tty/ttyGS0/ ] ; then
	systemctl start serial-getty@ttyGS0.service || true
fi
