#!/bin/bash
PATH="$PATH:/usr/bin/"
DISPLAY="1"
DEPTH="16"
GEOMETRY="1024x576"
OPTIONS="-depth ${DEPTH} -geometry ${GEOMETRY} :${DISPLAY}"
PROG=/usr/bin/vncpasswd
VNCPASS="respeaker"

case "$1" in
start)
/usr/bin/expect <<EOF
spawn "$PROG"
expect "Password:"
send "$VNCPASS\r"
expect "Verify:"
send "$VNCPASS\r"
expect "Would"
send "n\r"
expect eof
exit
EOF
/usr/bin/vncserver ${OPTIONS}
;;

stop)
/usr/bin/vncserver -kill :${DISPLAY}
;;

restart)
$0 stop
$0 start
;;
esac
exit 0
