.TH BLUETOOTHCTL "1" "May 2013"
.SH NAME
bluetoothctl \- bluetooth control tool
.SH SYNOPSIS
.B bluetoothctl
.SH DESCRIPTION
\fBbluetoothctl\fP is bluetooth control tool

.SH USAGE
bluetoothctl [options]

Help Options:
  \fB-h\fP, \fB--help\fP Show help options

Application Options:
  \fB-v\fP, \fB--version\fP Show version information and exit
  \fB-a\fP, \fB--agent=CAPABILITY\fP Register agent handler

.SH AUTHOR
This manual page was written by Nobuhiro Iwamatsu <iwamatsu@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
