.TH BMON "1" "May 2013"
.SH NAME
btmon \- Bluetooth monitor
.SH SYNOPSIS
.B btmon
.SH DESCRIPTION
\fBbtmon\fP is Bluetooth monitor

.SH USAGE
btmon [options]

Options:
  \fB-r\fP, \fB--read\fP <file>      Read traces in btsnoop format
  \fB-w\fP, \fB--write\fP <file>     Save traces in btsnoop format
  \fB-s\fP, \fB--server\fP <socket>  Start monitor server socket
  \fB-i\fP, \fB--index\fP <num>      Show only specified controller
  \fB-t\fP, \fB--time\fP             Show time instead of time offset
  \fB-T\fP, \fB--date\fP             Show time and date information
  \fB-S\fP, \fB--sco\fP              Dump SCO traffic
  \fB-h\fP, \fB--help\fP             Show help options

.SH AUTHOR
This manual page was written by Nobuhiro Iwamatsu <iwamatsu@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
