.TH GATTTOOL "1" "Aug 2015"
.SH NAME
gatttool \- tool for Bluetooth Low Energy device
.SH SYNOPSIS
.B  gatttool
.SH DESCRIPTION
\fBgatttool\fP is tool that can be used to manipulate these attributes with a Bluetooth Low Energy device.
.SH USAGE
  gatttool [OPTION...]

Help Options:
  \fB-h\fP, \fB--help\fP                                  Show help options
  \fB-h\fP, \fB--help\fP                                  Show help options
  \fB--help-all\fP                                  Show all help options
  \fB--help-gatt\fP                                 Show all GATT commands
  \fB--help-params\fP                               Show all Primary Services/Characteristics arguments
  \fB--help-char-read-write\fP                      Show all Characteristics Value/Descriptor Read/Write arguments

Application Options:
  \fB--i\fP, \fB---adapter=hciX\fP                        Specify local adapter interface
  \fB--b\fP, \fB---device=MAC\fP                          Specify remote Bluetooth address
  \fB--t\fP, \fB---addr-type=[public | random]\fP         Set LE address type. Default: public
  \fB--m\fP, \fB---mtu=MTU\fP                             Specify the MTU size
  \fB--p\fP, \fB---psm=PSM\fP                             Specify the PSM for GATT/ATT over BR/EDR
  \fB--l\fP, \fB---sec-level=[low | medium | high]\fP     Set security level. Default: low
  \fB--I\fP, \fB---interactive\fP                         Use interactive mode

.SH AUTHOR
This manual page was written by Nobuhiro Iwamatsu <iwamatsu@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
